name: FusionAR APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # install dependencies from package.json
      - name: Install packages
        run: npm install

      # install capacitor android
      - name: Install Capacitor Android
        run: npm install @capacitor/android

      # init capacitor if missing
      - name: Init Capacitor
        run: |
          npx cap init FusionAR com.fusion.ar --web-dir=www || true

      # ADD ANDROID PLATFORM
      - name: Add Android platform
        run: |
          npx cap add android || true

      # NOW sync/copy works
      - name: Sync Capacitor
        run: |
          npx cap sync android

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FusionAR-APK
          path: android/app/build/outputs/apk/debug/*.apk
